site_name: "PMST-Vaiphei: Person Marking in Vaiphei (South-Central Trans-Himalayan)"
docs_dir: docs
theme:
  palette:
    primary: pink
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
plugins:
  - paralex:
      paralex_package_path: "pmst-vaiphei.package.json"
      layout_tables:
        - tense_aspect
      layout_rows:
        - person
        - number
        - clusivity
      layout_columns:
        - polarity
extra_javascript:
  - column-filters.js
repo_url: https://github.com/isw-unibe-ch/PMST-Vaiphei
